---
# Your Economy plugin name
# Available: BedrockEconomy, EconomyAPI, Auto
economy: "Auto"

# Message for WhaleAlert
# Tag:
# {name} Sender Name
# {target} Target Name
# {amount} Amount of Transferred Money
# {economy} Name of Economy
# {line} New Line
message: "§a!!!!!! {amount} #{economy}, transfered from Unknow wallet to Unknow wallet"

# Minimum Transferred money for WhaleAlert
minimum: 100000

# Discord Webhook
discord:
 enable: false # true / false Discord Webhook
 webhook: "" # Your webhook url including https://
 name: "WhaleAlert" # Name Webhook
 # If You enable Embeds Message, WhaleAlert content
 # Will be in Embeds
 embeds: # Embeds message Webhook
  enable: false # For Embeds message Discord
  # Title for Message Discord
  title: "WhaleAlert"
  # Color for left In HTML Color
  color: "80FF00"
  # Footer Text
  footer: "Transaction from play.blabla.com"
...
